"""init

Revision ID: c1e81af8e1c6
Revises: 
Create Date: 2021-09-14 18:52:17.391769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e81af8e1c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('condition_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('condition_number')
    )
    op.create_table('energy',
    sa.Column('time_on_clock', sa.DateTime(), nullable=False),
    sa.Column('generated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time_on_clock')
    )
    op.create_index(op.f('ix_energy_time_on_clock'), 'energy', ['time_on_clock'], unique=False)
    op.create_table('operating_mode',
    sa.Column('mode_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('expenses_per_second', sa.REAL(), nullable=True),
    sa.Column('equipment_wear_and_tear_per_hour', sa.Integer(), nullable=True),
    sa.Column('generated_energy', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mode_number')
    )
    op.create_table('resources',
    sa.Column('time_on_clock', sa.DateTime(), nullable=False),
    sa.Column('remains', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time_on_clock')
    )
    op.create_index(op.f('ix_resources_time_on_clock'), 'resources', ['time_on_clock'], unique=False)
    op.create_table('workshop',
    sa.Column('workshop_number', sa.Integer(), nullable=False),
    sa.Column('workshop_name', sa.String(length=30), nullable=True),
    sa.Column('expenses', sa.REAL(), nullable=True),
    sa.Column('condition_number', sa.Integer(), nullable=True),
    sa.Column('mode_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition_number'], ['condition.condition_number'], ),
    sa.ForeignKeyConstraint(['mode_number'], ['operating_mode.mode_number'], ),
    sa.PrimaryKeyConstraint('workshop_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop')
    op.drop_index(op.f('ix_resources_time_on_clock'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('operating_mode')
    op.drop_index(op.f('ix_energy_time_on_clock'), table_name='energy')
    op.drop_table('energy')
    op.drop_table('condition')
    # ### end Alembic commands ###
